import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-dvh flex-col antialiased`}
      >
        <div className="flex w-full flex-1 flex-col">{children}</div>
        <Toaster />
        <footer className="bg-accent mt-auto w-full gap-1 p-8">
          <div className="space-y-1 p-1 text-xs font-medium">
            <p>&copy; 2026 Zarpdon.</p>

            <p className="text-muted-foreground">
              Todos os direitos reservados.
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
