import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";

import ConditionalFooter from "@/components/common/structure-or-layout/conditional-footer";
import ConditionalHeader from "@/components/common/structure-or-layout/conditional-header";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/providers/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-dvh flex-col antialiased`}
      >
        <ReactQueryProvider>
          <div className="flex w-full flex-1 flex-col">
            <ConditionalHeader />
            {children}
          </div>
        </ReactQueryProvider>
        <Toaster position="bottom-left" />
        <ConditionalFooter />
      </body>
    </html>
  );
}
